services:
  - type: web
    name: stremio-crunch-addon
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: stremio-crunch-db
          property: connectionString

databases:
  - name: stremio-crunch-db
    plan: free
    databaseName: stremiocrunch
    user: stremiocrunch
